version: '3.10'
services:
#  nginx:
#    container_name: dev_web
#    restart: on-failure
#    image: nginx:1.19.8
#    volumes:
#      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
#      - static_volume:/app/static
#    ports:
#      - 80:80
#    depends_on:
#      - web
  web:
    container_name: dev_backend
    build: .
    restart: always
    env_file: dev.env
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/app
#     - static_volume:/app/static
    depends_on:
     - db
  db:
    container_name: dev_db
    image: postgres:12.0-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
#    env_file: dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
#  static_volume:
  postgres_data: